FROM python:3.11

WORKDIR /app

# Install git for pip installations
RUN apt-get update && apt-get install -y git

# Copy your app
COPY . /app/

# Upgrade pip and install Cython and numpy first
RUN pip install --upgrade pip
RUN pip install Cython numpy

# Install remaining dependencies
RUN pip install -r requirements.txt

# Start the Django app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
