FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y git


COPY . /app/

RUN pip install --upgrade pip
RUN pip install Cython numpy

RUN pip install -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
